### ISSUE TITLE
需要证书的服务是手动下载证书还是自动下载？

### ISSUE THREAD

**Issue by martinzu** [Pigeonszz/acme.actions#1]
能说下需要证书的设备怎么自动从 repo 上下载证书么？我做了一个 bash，大致原理是：
1. 中心服务器通过 ACME 申请泛域名；
2. 通过 SCP 拷贝到远端；
3. 并通过 SSH 远程执行命令重启服务；
4. 在本地通过 openssl 检测证书可用性；
5. 最后把日志发给指定邮箱；

这个逻辑感觉中心服务器如果一旦被黑，所有服务器全完

**Comment by Pigeonszz** [comment]
项目更新了一下，现在证书种类目录下会生成随机数 (默认是openssl rand -hex 32) 命名的目录，证书则放在随机数目录内
~~写出bug了~~ bug应该修完了
远程访问可以试试这个[项目](https://github.com/cmliu/CF-Workers-Raw)，用Cloudflare Workers做中间件
就算别人有TOKEN，也获取不到其它随机数目录内的证书

**Comment by Pigeonszz** [comment]
既然是ACME就要做全套嘛
